- alias: Rule 1 Light on in the evening
  trigger:
  - platform: sun
    event: sunset
    offset: -01:00:00
  action:
    service: homeassistant.turn_on
    entity_id: group.evelights

- alias: Set Spotify Playlist
  trigger:
  - platform: state
    entity_id: input_select.spotify_playlist
  condition:
  - condition: template
    value_template: '{{ not is_state_attr(''media_player.spotify'', ''source'', states(''input_select.spotify_playlist''))
      }}'
  action:
  - service: media_player.media_play
    entity_id: media_player.spotify
    data_template:
      source: '{{ states(''input_select.spotify_playlist'') }}'

- action:
  - data:
      brightness: 255
      color_name: green
      entity_id: light.sn1_led
      flash: short
    service: light.turn_on
  - data:
      brightness: 255
      color_name: green
      entity_id: light.60019495eaf2_1921681133
    service: light.turn_on
  - data:
      entity_id: switch.redled1
    service: switch.turn_on
  alias: Stair lights on motion
  condition: []
  id: '1522613484374'
  trigger:
  - entity_id: sensor.sn1_pir
    from: standby
    platform: state
    to: motion detected

- alias: Turn off stair light 5 minutes after last movement
  trigger:
    platform: state
    entity_id: sensor.sn1_pir
    to: standby
    for:
      minutes: 5
  action:
    service: light.turn_off
    entity_id: light.60019495eaf2_1921681133

- alias: Turn off bathroom light 15 minutes after last movement
  trigger:
    platform: state
    entity_id: sensor.bathroom_pir
    to: '0'
    for:
      minutes: 15
  action:
    service: homeassistant.turn_off
    entity_id: switch.rfone

- action:
  - data:
      entity_id: light.60019495eaf2_1921681133
    service: homeassistant.turn_on
  - data:
      entity_id: switch.redled2
    service: homeassistant.turn_on
  alias: Upstairs lights on motion
  condition: []
  id: '1522687477023'
  trigger:
  - entity_id: sensor.sn2_pir
    from: standby
    platform: state
    to: motion detected
- action:
  - data:
      entity_id: switch.redled1
    service: homeassistant.turn_off
  alias: Stairs no motion led off
  condition: []
  id: '1524074287908'
  trigger:
  - entity_id: sensor.sn1_pir
    from: motion detected
    platform: state
    to: standby

- action:
  - data:
      entity_id: switch.redled2
    service: homeassistant.turn_off
  alias: Upstairs no motion led2 off
  condition: []
  id: '1524074445195'
  trigger:
  - entity_id: sensor.sn2_pir
    from: motion detected
    platform: state
    to: standby

- action:
  - data:
      entity_id: switch.redled3
    service: homeassistant.turn_off
  alias: Room no motion led3 off
  condition: []
  trigger:
  - entity_id: binary_sensor.pir_room
    from: 'on'
    platform: state
    to: 'off'

- action:
  - data:
      entity_id: switch.redled3
    service: homeassistant.turn_on
  alias: Room motion led3 on
  condition: []
  trigger:
  - entity_id: binary_sensor.pir_room
    from: 'off'
    platform: state
    to: 'on'

- action:
  - data:
      entity_ id: switch.rfone
    service: homeassistant.turn_on
  alias: Bathroom lights on motion
  condition: []
  id: '1524345030729'
  trigger:
  - entity_id: sensor.bathroom_pir
    from: '0'
    platform: state
    to: '1'
