homeassistant:
  name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: 16
  unit_system: metric
  time_zone: Europe/London
  customize: !include customize.yaml
  customize_domain: !include domain.yaml
  packages: !include_dir_named packages
frontend: 
  themes: !include themes.yaml
  javascript_version: latest
  extra_html_url:
    - /local/custom_ui/state-card-custom-ui.html
    - /local/custom_ui/state-card-tiles.html
    - /local/custom_ui/state-card-hline.html
    - /local/custom_ui/state-card-script-custom-text.html
    - /local/custom_ui/state-card-mini-media-player.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-custom-ui-es5.html
    - /local/custom_ui/state-card-tiles.html
    - /local/custom_ui/state-card-hline_es5.html
    - /local/custom_ui/state-card-script-custom-text-es5.html
    - /local/custom_ui/state-card-mini-media-player_es5.html
panel_iframe:
  emby:
    title: 'Emby'
    url: 'http://localhost:8096/web/home.html'
    icon: mdi:emby
  nodered_flows:
    title: 'Node-RED Flows'
    url: 'http://hassio.local:1880'
    icon: mdi:nodejs
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://hassio.local:3218
python_script:


panel_custom:
  - name: floorplan
    sidebar_title: Floorplan Down
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include floorplan.yaml

  - name: floorplan
    sidebar_title: Floorplan Up
    sidebar_icon: mdi:home
    url_path: floorplan2
    config: !include floorplan2.yaml

# Enables configuration UI
config:

updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

recorder:
  purge_keep_days: 5

history:
  include:
    entities:
      - sun.sun
      - sensor.moon
      - device_tracker.ec88926884b5
      - device_tracker.ac3743505cb2
      - device_tracker.0021dfc45c05
      - device_tracker.04d6aa726da0
      - sensor.speedtest_download
      - sensor.speedtest_upload
      - sensor.met_office_wind_speed 
      - sensor.met_office_temperature
      - sensor.roomtemp
      - sensor.sn1_temperature    
      - sensor.sn2_temperature  

history_graph:
  gr1:
    name: Family
    entities:
      - device_tracker.ec88926884b5
      - device_tracker.ac3743505cb2
      - device_tracker.0021dfc45c05
      - device_tracker.04d6aa726da0
    hours_to_show: 240
    refresh: 120

  gr2:
    name: Temperature
    entities:
      - sensor.sn1_temperature    
      - sensor.sn2_temperature  
    hours_to_show: 120
    refresh: 120
  gr3:
    name: Sun
    entities:
      - sun.sun
    hours_to_show: 240

  gr4:
    name: Outside Temps
    entities:
      - sensor.met_office_temperature
    hours_to_show: 120
    refresh: 120

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
weather:
  - platform: metoffice
    api_key: !secret metoffice_api_key

  - platform: yweather 

binary_sensor:
  - platform: iss

  - platform: rpi_gpio
    ports:
      20: PIR Room
      21: button1
      16: button2


camera:
  - platform: generic
    name: ISS
    still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.binary_sensor.iss.attributes.lat }},{{ states.binary_sensor.iss.attributes.long }}&zoom=5&size=500x500&maptype=roadmap&markers=color:blue%7Clabel:P%7C{{ states.binary_sensor.iss.attributes.lat }},{{ states.binary_sensor.iss.attributes.long }}
    limit_refetch_to_url_change: true

ifttt:
  key: !secret ifttt_key

# Text to speech
tts:
  - platform: google

# Cloud
cloud:
  alexa:
    filter:
      exclude_domains:
        - script
        - automation
        - group
        - lock
        - media_player
        - switch
        - cover
        - alert
        - sensor

      

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
switch: !include switches.yaml
sensor: !include sensors.yaml 
media_player: !include mediaplayers.yaml

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.1.0/24
    home_interval: 10
    interval_seconds: 60
    exclude:
     - 192.168.1.78
     - 192.168.1.115
     - 192.168.1.116
     - 192.168.1.120
     - 192.168.1.66
     - 192.168.1.119
     - 192.168.1.254
  
mqtt:
  discovery: true

light:  
  - platform: mqtt_json  
    name: "SN1 LED"  
    state_topic: "bruh/sensornode1"  
    command_topic: "bruh/sensornode1/set"  
    brightness: true  
    flash: true  
    rgb: true  
    optimistic: false  
    qos: 0 

  - platform: flux_led
    automatic_add: True

android_ip_webcam:
  - host: 192.168.1.118
    port: 8080
    sensors:
      - audio_connections
      - battery_level
      - battery_temp
      - light
      - pressure
    switches:
      - exposure_lock
      - ffc
      - focus
      - gps_active
      - night_vision
      - overlay
      - torch
      - whitebalance_lock
      - video_recording

  - host: 192.168.1.66
    port: 8080
    sensors:
      - audio_connections
      - battery_level
      - battery_temp
      - light
      - pressure
    switches:
      - exposure_lock
      - ffc
      - focus
      - gps_active
      - night_vision
      - overlay
      - torch
      - whitebalance_lock
      - video_recording

  - host: 192.168.1.124
    port: 8080
    sensors:
      - audio_connections
      - battery_level
      - battery_temp
      - light
      - pressure
    switches:
      - exposure_lock
      - ffc
      - focus
      - gps_active
      - night_vision
      - overlay
      - torch
      - whitebalance_lock
      - video_recording
  
input_select:
  spotify_playlist:
    name: Playlist
    options: 
      - Claire
      - faves
      - 30's 40's 50's
      - Ash - 1977
      - Garbage - Bleed Like Me
      - Garbage - Garbage
      - Garbage - Version 2.0
      - Garbage - Beautiful Garbage
      - Garbage - Not Your Kind Of People
      - Garbage - Strange Little Birds
      - AFI
      - Alice in Chains - Dirt
      - Alice in Chains - Facelift
      - Ariana Granda - Dangerous Women
      - Ash - The Best Of
      - The Beautiful South - Blue is the Colour
      - The Beautiful South - Carry on up the Charts
      - The Beautiful South - Choke
      - The Beautiful South - Mioaw
      - The Beautiful South - Quench
      - Bitch Alert - Kill your Darlings
      - Courtney Love - America's Sweetheart
      - The distillers - Coral Fang
      - Dropkick Murpheys - 11 Short Stories of Pain and Glory
      - The Duke Spirit - Cut Across the Land
      - Elastica - elastica
      - Elastica - The Menace
      - Eminem - The Revival
      - The Epoxies - Stop the Future
      - The Epoxies - Synthesized


arduino:
  port: /dev/ttyACM0

input_text:
  dummy_player_mini:
    name: Room
  dummy_player_kitchen:
    name: Kitchen
  dummy_window_right:
    name: Window Right
  dummy_player_box:
    name: Tablet Box






  




